name: "Government"
description: "A site to use for my AP Government notes."
chapters: [1, 2, 3]

email: "bionicle.dragon@gmail.com"
github: "porglezomp"
twitter: "stickfigure42"
repo: "porglezomp.github.io/porglezomp/ap-gov"

url: "http://localhost:5000"

markdown: redcarpet
redcarpet:
    extensions: ["smart"]

permalink: pretty
highlighter: pygments

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
